[package]
name = "falion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
regex = "1.5.5"
urlencoding = "2.1.0"
