edition = "2021"
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
normalize_doc_attributes = true
imports_granularity = "Module"
normalize_comments = true
reorder_impl_items = true
use_try_shorthand = true
newline_style = "Unix"
format_strings = true
wrap_comments = true
