---
name: 🐞 Bug Report
title: "[bug] "
description: Report a bug
labels: ["type: bug", "status: needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/Obscurely/falion/issues?q=is%3Aissue) about this problem first.
        2. Make sure `rustc` and all relevant falion packages are up to date.
        3. Make sure it's an issue with falion and not something else you are using.
        4. Remember to follow the community guidelines and be friendly.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: info
    attributes:
      label: Platform and versions
      description: Platform, OS & Version used.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log file
      description: |
        The log file from the session on which the issue happened. Available at:
        On windows: C:\users\yourname\AppData\Temp\falion\the_file.log
        On macOS: $HOME/Library/Caches/falion/the_file.log
        On Linux: $HOME/.cache/falion/the_file.log
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
