// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton } from "std-widgets.slint";

export component MainWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    min-width: 250px;
    min-height: 100px;
    title: "Falion";
    icon: @image-url("../assets/images/logo.png");
    callback query-enter(string);

    VerticalBox {
        HorizontalBox {
            text-search := LineEdit {
                max-height: 80px;
                font-size: 24px;
                placeholder-text: "What are you wondering about?";
                accepted(text) => {
                    root.query-enter(self.text);
                    self.text = "";
                }
            }
            btn-search := Button {
                max-height: 100px;
                icon: @image-url("../assets/images/logo.png");
                enabled: text-search.text != "";
                clicked => {
                    root.query-enter(text-search.text);
                    text-search.text = "";
                }
            }
        }
        btn := Button {
            text: "Search";
            clicked => {
            }
        }
    }
}
