// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton } from "std-widgets.slint";

export component MainWindow inherits Window {
    preferred-width: 1250px;
    preferred-height: 750px;
    min-width: 750px;
    min-height: 500px;
    default-font-size: 24px;
    title: "Falion";
    icon: @image-url("../assets/images/logo.png");

    callback query-enter(string);
    callback sof-enter();
    callback se-enter();
    callback gg-enter();
    callback gfg-enter();
    callback ddg-enter();
    callback back-enter();
    callback next-enter();

    in property <string> sof-result: " ";
    in property <string> se-result: " ";
    in property <string> gg-result: " ";
    in property <string> gfg-result: " ";
    in property <string> ddg-result: " ";

    in property <bool> is-sof: false;
    in property <bool> is-se: false;
    in property <bool> is-gg: false;
    in property <bool> is-gfg: false;
    in property <bool> is-ddg: false;
    
    in property <bool> is-back: false;
    in property <bool> is-next: false;

    in property <string> error: "";

    VerticalBox {
        min-width: 750px;
        min-height: 500px;
        HorizontalBox {
            text-search := LineEdit {
                max-height: 80px;
                min-height: 40px;
                font-size: 28px;
                placeholder-text: "What are you wondering about?";
                enabled: true;
                accepted(text) => {
                    root.query-enter(self.text);
                }
            }
            btn-search := Button {
                min-width: 50px;
                max-height: 80px;
                min-height: 40px;
                icon: @image-url("../assets/images/logo.png");
                enabled: text-search.text != "";
                clicked => {
                    root.query-enter(text-search.text);
                }
            }
        }
        HorizontalBox {
            text-sof := Text {
                text: "(1) StackOverflow:";
                font-size: 24px;
                min-width: 220px;
                max-width: 220px;
                color: yellow;
            }
            btn-sof := Button {
                text: root.sof-result;
                max-height: 30px;
                enabled: root.is-sof;
                clicked => {
                    root.sof-enter();
                }
            }
        }
        HorizontalBox {
            text-se := Text {
                text: "(2) StackExchange:";
                font-size: 24px;
                min-width: 220px;
                max-width: 220px;
                color: yellow;
            }
            btn-se := Button {
                text: root.se-result;
                max-height: 30px;
                enabled: root.is-se;
                clicked => {
                    root.se-enter();
                }
            }
        }
        HorizontalBox {
            text-gg := Text {
                text: "(3) GitHub Gist:";
                font-size: 24px;
                min-width: 220px;
                max-width: 220px;
                color: yellow;
            }
            btn-gg := Button {
                text: root.gg-result;
                max-height: 30px;
                enabled: root.is-gg;
                clicked => {
                    root.gg-enter();
                }
            }
        }
        HorizontalBox {
            text-gfg := Text {
                text: "(4) GeeksForGeeks:";
                font-size: 24px;
                min-width: 220px;
                max-width: 220px;
                color: yellow;
            }
            btn-gfg := Button {
                text: root.gfg-result;
                max-height: 30px;
                enabled: root.is-gfg;
                clicked => {
                    root.gfg-enter();
                }
            }
        }
        HorizontalBox {
            text-dgg := Text {
                text: "(5) DuckDuckGO:";
                font-size: 24px;
                min-width: 220px;
                max-width: 220px;
                color: yellow;
            }
            btn-dgg := Button {
                text: root.ddg-result;
                max-height: 30px;
                enabled: root.is-ddg;
                clicked => {
                    root.ddg-enter();
                }
            }
        }
        HorizontalBox {
            text-error := Text {
                text: root.error;
                font-size: 24px;
                color: red;
            } 
        }
        HorizontalBox {
          spacing: 300px;
          Text {}
        }
        HorizontalBox {
            btn-back := Button {
                max-height: 30px;
                enabled: root.is-back;
                text: "<- Back";
                clicked => {
                    root.back-enter();
                }
            }
            spacing: 500px;
            btn-next := Button {
                max-height: 30px;
                enabled: root.is-next;
                text: "Next ->";
                clicked => {
                    root.next-enter();
                }
            }
        }
    }
}
