---
name: Greetings
on: [pull_request_target, issues]
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi, I am really greatful you want to contribute to\
            my project. I will check this as soon as I can."
          pr-message: "Hi, thank you so much for contributing to my project,\
            it means a lot. I will check this as soon as I can."
